### ISSUE TITLE
Inconsistent naming for npm access token secret

### ISSUE THREAD

**Issue by SorinTheSleuth** [trevinhofmann/eleventh#12]
The environment variable `NODE_AUTH_TOKEN` is used within the 'Publish to npm' step to authenticate against the npm registry. However, the given placeholder secret is named `NPM_ACCESS_TOKEN`. Secrets are case-sensitive and must match exactly. 

If the actual secret stored in GitHub is `NPM_ACCESS_TOKEN`, this will result in an authentication error and the publish action will fail due to incorrect credentials. The name of the secret in the workflow file must match the name of the secret stored in the repository settings.

To fix this bug, ensure that the secret name is consistent across the repository settings and the workflow file. Replace `NODE_AUTH_TOKEN` with the correct secret name as stored in the GitHub repository secrets.

If `NPM_ACCESS_TOKEN` is the correct secret name, update the workflow as follows:

```yaml
- name: Publish to npm
  run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
```

To:

```yaml
- name: Publish to npm
  run: npm publish
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
```
